### ISSUE TITLE
4.25. Shipping build fails to launch due to shader compiliation issues.

### ISSUE THREAD

**Issue by MarkJGx** [hugoattal/DarkerNodes#131] opened 2021-02-06 14:46 UTC
I want to use this theme. Unfortunately when packaging a shipping game with this editor plugin enabled, it causes the Windows shipping build to crash with a missing WorldGridMaterial (due to failed shader compilation while cooking). While building for Linux under the Vulkan RHI, the shader cooker starts throwing out dialog messages that it's failing to build DarkerNodes Shapes.usf. Doesn't throw out any errors on the Windows DX11/DX12 build, but Windows build doesn't launch regardless. The most peculiar thing is that this is a editor plugin, yet it's interfering with a non-editor shipping build.
Linux
![linux-shipping-fial](https://user-images.githubusercontent.com/38701409/107121390-d4d65280-689a-11eb-90cb-47778d7b7d0a.png)
Windows
![windows-launch-fail](https://user-images.githubusercontent.com/38701409/107121393-d56ee900-689a-11eb-8fcb-23d0351f3732.png)

**Comment by TheHerobrine** [comment] 2021-02-06 15:27
Hum, I still can't understand why Unreal does anything at building shipping time when the plugin is explicitely marked as Editor plugin...
![image](https://user-images.githubusercontent.com/4563971/107122267-01886b00-6897-11eb-8a09-742187d52196.png)

But regardless:
- I didn't get any feedback that Darker Nodes is crashing shipping build in Windows, that's concerning...
- It may have something to do with Vulkan? I never tried Vulkan with Unreal Engine, is HLSL supported?

What seems to bother your compiler is this static word, but I don't understand why it would be unexpected...
![image](https://user-images.githubusercontent.com/4563971/107122340-83789400-6897-11eb-9abb-15620d06ff5d.png)

I'll dig into that, in the meantime I suggest two solutions:
- If possible, do not commit you `.uproject` file with DarkerNodes, or launch your build from a version of your `.uproject` file without Darker Nodes.
- If your building machine is different from your development machine, you may try to these steps to make DarkerNodes defaultly activated on your development machine, not modifying your uproject: https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#how-can-i-make-darker-nodes-to-be-applied-on-every-project

In any case, I know it's not ideal (I'm very sorry for this), and I'll try to find a solution 😕

**Comment by TheHerobrine** [comment] 2021-02-06 15:31
@MarkJGx Also, seeing this issue: https://github.com/adamrehn/ue4-docker/issues/83, do you have 4.25.1 update? Or do you run a custom version of the engine?

**Comment by MarkJGx** [comment] 2021-02-06 15:44
4.25.3 fork locally built. #adamrehn/ue4-docker#83 looks unrelated since I'm cross-compiling a game project with a pre-built engine.
I bet that the Windows DX12/DX11 RHI build is suffering from the same issue as the Vulkan RHI Linux build, but isn't being as verbose. From my understanding unreal shader code translates between RHI's seamlessly, so a Vulkan specific bug is unlikely.

**Comment by TheHerobrine** [comment] 2021-02-07 11:56
@MarkJGx Arg, I can't reproduce at all, everything seems to work fine on my end on Windows... (Build and launch)

If you go into "Edit/Editor Preferences/Darker Nodes Plugins" and you click on "Fix Missing Elements", do you have anything special on the log? Does it change the outcome?

Also, I'm not very familiar with cross compiling/building in command line... Can you explain me quickly how to build a project to Linux under Vulkan RHI?

**Comment by MarkJGx** [comment] 2021-02-07 17:44
This will build a Linux standalone shipping build without the editor.
`RunUAT.bat BuildCookRun -project=C:/Users/user/Documents/UnrealProjects/privacy/Privacy.uproject -nocompile -nocompileeditor -installed -rocket -nop4 -licensee -clientconfig=Shipping -serverconfig=Shipping -platform=Linux -cook -iterate -iterativecooking -package -stage -stagingdirectory=C:\Users\user\Documents\UnrealProjects\privacy\Scripts\Output\Linux -build -pak -prereqs -distribution`

DefaultEngine.ini settings for the Vulkan RHI on Linux.
`[/Script/LinuxTargetPlatform.LinuxTargetSettings]
SpatializationPlugin=
ReverbPlugin=
OcclusionPlugin=
+TargetedRHIs=SF_VULKAN_SM5`

**Comment by TheHerobrine** [comment] 2021-02-07 18:47
Ok, I downloaded the clang thing and the Linux option of the Unreal Engine 4.26.
I did not change the DefaultEngine.ini since you said that a Vulkan specific bug was unlikely.
I launched the exact same command line you gave (only changing the project directories)
And I think it worked, I didn't have any problem at all...

![image](https://user-images.githubusercontent.com/4563971/107156188-31aa3980-697d-11eb-813b-bb8e4243a6cb.png)

Could you try the same thing from a blank project? If you don't have time for this, there's no problem...

**Comment by MarkJGx** [comment] 2021-02-10 17:49
After pressing "Fix Elements" and restarting:
![Screenshot (278)](https://user-images.githubusercontent.com/38701409/107549555-a2995d80-6bd8-11eb-8cf6-733f90231f89.png)

We don't use Niagara, and it's completely disabled for our whole project.

**Comment by TheHerobrine** [comment] 2021-02-10 18:13
Hum, Darker Nodes requires Niagara to update the Niagara interface.
I'm not planning on removing Niagara support, and I can't make it an option since the Niagara requirement is in the `.uplugin`...
But if you want to use Darker Nodes while keeping Niagara disabled, I could make a custom build for you!

About the error you get, it feels pretty weird... Is the plugin directly inside your project `Plugins` folder? Or in the marketplace folder of the engine? Is the plugin activated at all? I think you might want to:
- disable the plugin on your project
- delete the plugin
- delete your `Binary` and `Intermediate folder`
- rebuild your project (so it's clean)
- redownload the plugin

**Comment by MarkJGx** [comment] 2021-02-10 18:49
Started writing this right after my original post:
I removed any mention of Niagara from the .uplugin's .json and plugin module's build.cs, also removed any reference to Niagara editor in the plugins native code, including the slate styling code. After that the editor was still failing on a different shader error, involving Button.usf. I ended up going in and removing the commented `#include Button.usf` code, for some reason that actually did something?
Did the fix elements thing again and no errors on launch. Just compiled the shipping builds for all platforms with some slight hitches due to iterative cooking, cleared out the local Intermediate/Binaries directories and tried again, can confirm that the Windows version builds and runs without any shader errors, however the Linux builds still have the same issue.

I could setup a private repo with the modifications if you'd like.

**Comment by TheHerobrine** [comment] 2021-02-10 18:57
Hum, the thing is that you won't be using the shaders function used in the `.usf`... Unless you C/C their content inside the material custom node (which not ideal from a dev perspective 😅). But I'll probably end up doing this if that fix your problem.

By any chance, don't have any `ResetAllShaderSourceDirectoryMappings()` call in your code/plugins?

**Comment by MarkJGx** [comment] 2021-02-10 19:06
Nope. No ResetAllShaderSourceDirectoryMappings in any plugins/project code.

**Comment by TheHerobrine** [comment] 2021-02-10 19:38
So, does the `Shaders` folder exist under the `DarkerNodes` folder with a bunch of `.usf` files (including `Button.usf`) inside it? If it does, I'm really clueless on what happen...

**Comment by MarkJGx** [comment] 2021-02-10 19:40
It does.

**Comment by MarkJGx** [comment] 2021-02-10 20:26
Fixed. Disabled `r.ShaderDevelopmentMode`

**Comment by TheHerobrine** [comment] 2021-02-10 20:38
Added on the FAQ: https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ

**Comment by jorgenpt** [comment] 2022-03-11 22:51
@hugoattal We are also hitting this problem -- we're on 4.27.2, and only the Android cook is hitting these warnings. We're running `Engine\Binaries\Win64\UE4Editor-Cmd.exe Project\Project.uproject -run=Cook  -TargetPlatform=Android_MultiClient -fileopenlog -unversioned -stdout -CrashForUAT -unattended -NoLogTimes`, and this is the output:

```
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/Panel.Panel for platform GLSL_ES3_1_ANDROID, Default Material will be used in game.
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Display: /DarkerNodes/lib/Shapes.usf(12): error: syntax error, unexpected STATIC
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/HeaderBox.HeaderBox for platform SF_VULKAN_ES31_ANDROID, Default Material will be used in game.
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Display: /DarkerNodes/lib/Shapes.usf(12): error: syntax error, unexpected STATIC
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/HeaderBox.HeaderBox for platform GLSL_ES3_1_ANDROID, Default Material will be used in game.
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Display: /DarkerNodes/lib/Shapes.usf(12): error: syntax error, unexpected STATIC
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/Button.Button for platform SF_VULKAN_ES31_ANDROID, Default Material will be used in game.
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Display: /DarkerNodes/lib/Shapes.usf(12): error: syntax error, unexpected STATIC
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Warning: Failed to compile Material /DarkerNodes/Materials/Button.Button for platform GLSL_ES3_1_ANDROID, Default Material will be used in game.
[2022-03-11T22:25:21.942Z]     LogShaderCompilers: Display: /DarkerNodes/lib/Shapes.usf(12): error: syntax error, unexpected STATIC
```

As far as I can tell, we aren't using `r.ShaderDevelopmentMode`

**Comment by hugoattal** [comment] 2022-03-13 14:49
@jorgenpt Thank you for this, it will be updated for the next version!

**Comment by hugoattal** [comment] 2022-04-06 00:25
Ready for version 3!

**Closed** 2022-05-05 20:48 UTC
Labels: bug, ready
